spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://49.235.24.173:3306/timber?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      username: root
      password: roottoor
  profiles:
    active: dev
  mvc:
    view:
      suffix: .html
  rabbitmq:
    host: localhost

    username: guest
    password: guest

server:
  port: 80

rabbitmq:
  zeusexchange: zeus_waybill_exchange
