mybatis:
  type-aliases-package: cn.eskyzdt.modules.dao
  mapper-locations: classpath*:mapper/*Dao.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://49.235.24.173:3306/timber_va?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      username: root
      password: root
#    profiles:
#    active: dev
