-- CREATE DATABASE timber;
-- USE timber;
-- drop table if exists `user`;
CREATE TABLE `user`(
	 `id` int(20) NOT NULL AUTO_INCREMENT,
	 `username` VARCHAR(20) NOT NULL COMMENT '用户名',
	 `password` VARCHAR(20) DEFAULT NULL COMMENT '密码',
	 `phone` VARCHAR(20) DEFAULT NULL COMMENT '电话',
	 `email` VARCHAR(20) DEFAULT NULL COMMENT '邮箱',
	 `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建时间',
	 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='用户表';

-- 创建物品表
-- DROP TABLE IF EXISTS `item`;
CREATE TABLE `item` (
	`id` INT ( 20 ) UNSIGNED NOT NULL AUTO_INCREMENT,
	`item_name` VARCHAR ( 20 ) NOT NULL COMMENT '道具名',
	`serial` BIGINT ( 20 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT '道具序列号',
	`item_type` INT ( 5 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT '道具类型',
	`ad` BIGINT ( 20 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT '物攻',
	`ap` BIGINT ( 20 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT '魔攻',
	`ad_def` BIGINT ( 20 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT '物防',
	`ap_def` BIGINT ( 20 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT '魔防',
PRIMARY KEY ( `id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMMENT = '物品表';